import { LanguageMetadata } from '../types/languages';

export const SUPPORTED_LANGUAGES: LanguageMetadata[] = [
  {
    code: 'ta',
    name: 'Tamil',
    nativeName: 'தமிழ்',
    script: 'Tamil',
    region: 'Tamil Nadu, Puducherry',
    tier: 'TIER_1_SIMULATED',
    samplePrompt: 'எனக்கு நாளை மாலை AC சர்வீஸ் வேண்டும்',
    sampleIntent: 'AC Deep Clean & Service',
    isScheduled22: true,
  },
  {
    code: 'en-IN',
    name: 'English',
    nativeName: 'English',
    script: 'Latin',
    region: 'Pan-India / Global',
    tier: 'TIER_1_SIMULATED',
    samplePrompt: 'Need an electrician to fix fan regulator tomorrow morning',
    sampleIntent: 'Fan Regulator Repair',
    isScheduled22: false,
  },
];

export const FUTURE_ROADMAP_LANGUAGES: LanguageMetadata[] = [
  {
    code: 'as',
    name: 'Assamese',
    nativeName: 'অসমীয়া',
    script: 'Bengali-Assamese',
    region: 'Assam',
    tier: 'TIER_2_ROADMAP',
    samplePrompt: 'মোক কাইলৈ পুৱা এচি চাৰ্ভিচিং লাগে',
    sampleIntent: 'AC Service',
    isScheduled22: true,
  },
  {
    code: 'bn',
    name: 'Bengali',
    nativeName: 'বাংলা',
    script: 'Bengali',
    region: 'West Bengal, Tripura',
    tier: 'TIER_2_ROADMAP',
    samplePrompt: 'আমার কাল সকালে এসি সার্ভিসিং দরকার',
    sampleIntent: 'AC Service',
    isScheduled22: true,
  },
  {
    code: 'brx',
    name: 'Bodo',
    nativeName: 'बड़ो',
    script: 'Devanagari',
    region: 'Assam, Bodoland',
    tier: 'TIER_2_ROADMAP',
    samplePrompt: 'आंनो गाबोन फुंआव एचि सार्भिसिं नांगौ',
    sampleIntent: 'AC Service',
    isScheduled22: true,
  },
  {
    code: 'doi',
    name: 'Dogri',
    nativeName: 'डोगरी',
    script: 'Devanagari',
    region: 'Jammu & Kashmir',
    tier: 'TIER_2_ROADMAP',
    samplePrompt: 'मिगी कल सबेरे एसी दी मरम्मत लोड़चदी ऐ',
    sampleIntent: 'AC Repair',
    isScheduled22: true,
  },
  {
    code: 'gu',
    name: 'Gujarati',
    nativeName: 'ગુજરાતી',
    script: 'Gujarati',
    region: 'Gujarat',
    tier: 'TIER_2_ROADMAP',
    samplePrompt: 'મને કાલે સવારે એસી સર્વિસ કરાવવું છે',
    sampleIntent: 'AC Service',
    isScheduled22: true,
  },
  {
    code: 'kn',
    name: 'Kannada',
    nativeName: 'ಕನ್ನಡ',
    script: 'Kannada',
    region: 'Karnataka',
    tier: 'TIER_2_ROADMAP',
    samplePrompt: 'ನನಗೆ ನಾಳೆ ಸಂಜೆ ಎಸಿ ಸರ್ವೀಸ್ ಬೇಕು',
    sampleIntent: 'AC Service',
    isScheduled22: true,
  },
  {
    code: 'ks',
    name: 'Kashmiri',
    nativeName: 'कॉशुर',
    script: 'Perso-Arabic / Devanagari',
    region: 'Jammu & Kashmir',
    tier: 'TIER_2_ROADMAP',
    samplePrompt: 'मे छु पगह सबहन एसी ठीक करनय',
    sampleIntent: 'AC Repair',
    isScheduled22: true,
  },
  {
    code: 'kok',
    name: 'Konkani',
    nativeName: 'कोंकणी',
    script: 'Devanagari',
    region: 'Goa, Coastal Karnataka',
    tier: 'TIER_2_ROADMAP',
    samplePrompt: 'म्हाका फाल्यां सकाळीं एसी दुरुस्ती जाय',
    sampleIntent: 'AC Repair',
    isScheduled22: true,
  },
  {
    code: 'mai',
    name: 'Maithili',
    nativeName: 'मैथिली',
    script: 'Devanagari',
    region: 'Bihar, Jharkhand',
    tier: 'TIER_2_ROADMAP',
    samplePrompt: 'हमरा काइल भोर में एसी सर्विस चाही',
    sampleIntent: 'AC Service',
    isScheduled22: true,
  },
  {
    code: 'ml',
    name: 'Malayalam',
    nativeName: 'മലയാളം',
    script: 'Malayalam',
    region: 'Kerala, Lakshadweep',
    tier: 'TIER_2_ROADMAP',
    samplePrompt: 'എനിക്ക് നാളെ വൈകുന്നേരം എസി സർവീസ് വേണം',
    sampleIntent: 'AC Service',
    isScheduled22: true,
  },
  {
    code: 'mni',
    name: 'Manipuri (Meitei)',
    nativeName: 'মৈতৈলোন্',
    script: 'Meitei Mayek',
    region: 'Manipur',
    tier: 'TIER_2_ROADMAP',
    samplePrompt: 'ঐহাক্না হয়েন অয়ুক এসি সর্ভিস তৌনিংই',
    sampleIntent: 'AC Service',
    isScheduled22: true,
  },
  {
    code: 'mr',
    name: 'Marathi',
    nativeName: 'मराठी',
    script: 'Devanagari',
    region: 'Maharashtra',
    tier: 'TIER_2_ROADMAP',
    samplePrompt: 'मला उद्या सकाळी एसी सर्व्हिसिंग हवी आहे',
    sampleIntent: 'AC Service',
    isScheduled22: true,
  },
  {
    code: 'ne',
    name: 'Nepali',
    nativeName: 'नेपाली',
    script: 'Devanagari',
    region: 'Sikkim, West Bengal',
    tier: 'TIER_2_ROADMAP',
    samplePrompt: 'मलाई भोलि बिहान एसी मर्मत गराउनु छ',
    sampleIntent: 'AC Repair',
    isScheduled22: true,
  },
  {
    code: 'or',
    name: 'Odia',
    nativeName: 'ଓଡ଼ିଆ',
    script: 'Odia',
    region: 'Odisha',
    tier: 'TIER_2_ROADMAP',
    samplePrompt: 'ମୋତେ କାଲି ସକାଳେ ଏସି ସର୍ଭିସ୍ ଦରକାର',
    sampleIntent: 'AC Service',
    isScheduled22: true,
  },
  {
    code: 'pa',
    name: 'Punjabi',
    nativeName: 'ਪੰਜਾਬੀ',
    script: 'Gurmukhi',
    region: 'Punjab, Delhi, Haryana',
    tier: 'TIER_2_ROADMAP',
    samplePrompt: 'ਮੈਨੂੰ ਕੱਲ੍ਹ ਸਵੇਰੇ ਏਸੀ ਸਰਵਿਸ ਦੀ ਲੋੜ ਹੈ',
    sampleIntent: 'AC Service',
    isScheduled22: true,
  },
  {
    code: 'sa',
    name: 'Sanskrit',
    nativeName: 'संस्कृतम्',
    script: 'Devanagari',
    region: 'Pan-India',
    tier: 'TIER_2_ROADMAP',
    samplePrompt: 'श्वः प्रभाते शीतक-यन्त्र-शोधनं वाञ्छामि',
    sampleIntent: 'AC Service',
    isScheduled22: true,
  },
  {
    code: 'sat',
    name: 'Santali',
    nativeName: 'ᱥᱟᱱᱛᱟᱲᱤ',
    script: 'Ol Chiki',
    region: 'Jharkhand, Odisha, West Bengal',
    tier: 'TIER_2_ROADMAP',
    samplePrompt: 'ᱜᱟᱯᱟ ᱥᱮᱛᱟᱜ ᱮᱥᱤ ᱥᱟᱨᱵᱷᱤᱥ ᱞᱟᱹᱠᱛᱤ ᱠᱟᱱᱟ',
    sampleIntent: 'AC Service',
    isScheduled22: true,
  },
  {
    code: 'sd',
    name: 'Sindhi',
    nativeName: 'سنڌي',
    script: 'Perso-Arabic / Devanagari',
    region: 'Gujarat, Maharashtra, Rajasthan',
    tier: 'TIER_2_ROADMAP',
    samplePrompt: 'مون کي سڀاڻي صبح جو اي سي سروس گهرجي',
    sampleIntent: 'AC Service',
    isScheduled22: true,
  },
  {
    code: 'te',
    name: 'Telugu',
    nativeName: 'తెలుగు',
    script: 'Telugu',
    region: 'Andhra Pradesh, Telangana',
    tier: 'TIER_2_ROADMAP',
    samplePrompt: 'నాకు రేపు సాయంత్రం ఏసీ సర్వీస్ కావాలి',
    sampleIntent: 'AC Service',
    isScheduled22: true,
  },
  {
    code: 'ur',
    name: 'Urdu',
    nativeName: 'اردو',
    script: 'Perso-Arabic',
    region: 'Telangana, UP, Bihar, J&K, Delhi',
    tier: 'TIER_2_ROADMAP',
    samplePrompt: 'مجھے کل صبح اے سی سروس کروانی ہے',
    sampleIntent: 'AC Service',
    isScheduled22: true,
  },
];
