import { UserAccount } from '../types/account';
import { MatchedProvider, Booking } from '../types/customer';
import { JobOpportunity, TechnicianEarnings } from '../types/technician';

export const INITIAL_USER_ACCOUNT: UserAccount = {
  id: 'usr_nexdo_001',
  name: 'Hariharasudhan',
  phone: '9876543210',
  dob: '24/08/2007',
  email: 'hariharasudhan@example.com',
  avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
  createdAt: '2026-01-15T10:00:00Z',
  customerProfile: {
    id: 'cust_001',
    name: 'Hariharasudhan',
    phone: '9876543210',
    dob: '24/08/2007',
    address: '42, Sengunthapuram 3rd Cross',
    city: 'Karur',
    district: 'Karur District, Tamil Nadu',
    pincode: '639002',
    preferredLanguage: 'ta',
    voiceAutoConfirm: true,
    savedAddresses: [
      {
        id: 'addr_home',
        label: 'Home',
        address: '42, Sengunthapuram 3rd Cross, Karur, TN 639002',
        isDefault: true,
      },
      {
        id: 'addr_work',
        label: 'Office',
        address: '15, Jawahar Bazaar, Karur, TN 639001',
        isDefault: false,
      },
    ],
  },
  technicianProfile: {
    id: 'tech_001',
    name: 'Ravi Kumar',
    phone: '9876543210',
    dob: '12/04/1996',
    address: '18, Sardar Patel Road, Adyar',
    city: 'Chennai',
    district: 'Chennai District, Tamil Nadu',
    pincode: '600020',
    capabilities: [
      { id: 'cap_ac_rep', code: 'AC_REPAIR', name: 'AC Repair & Diagnostics', category: 'HVAC & Cooling', experienceLevel: 'EXPERT', isCertified: true, active: true },
      { id: 'cap_ac_srv', code: 'AC_SERVICE', name: 'AC Deep Cleaning & Gas Refill', category: 'HVAC & Cooling', experienceLevel: 'EXPERT', isCertified: true, active: true },
      { id: 'cap_fan_rep', code: 'FAN_REPAIR', name: 'Ceiling & Exhaust Fan Repair', category: 'Electrical', experienceLevel: 'EXPERT', isCertified: true, active: true },
      { id: 'cap_elec_gen', code: 'ELECTRICAL_WORK', name: 'Wiring, MCB & Switchboard Work', category: 'Electrical', experienceLevel: 'INTERMEDIATE', isCertified: false, active: true },
      { id: 'cap_bike', code: 'BIKE_REPAIR', name: 'Two-Wheeler Service & Starting Fix', category: 'Automotive', experienceLevel: 'INTERMEDIATE', isCertified: false, active: true },
    ],
    serviceAreas: ['Adyar', 'Besant Nagar', 'Thiruvanmiyur', 'Kotturpuram'],
    radiusKm: 8,
    experienceYears: 7,
    rating: 4.9,
    completedJobsCount: 342,
    verificationStatus: 'VERIFIED',
    availabilityStatus: 'ONLINE',
    activeSubscription: {
      planId: 'monthly_pass',
      type: 'MONTHLY',
      title: 'Monthly Access Pass',
      price: 2499,
      activatedAt: '2026-09-01T00:00:00Z',
      expiresAt: '2026-10-01T23:59:59Z',
      isActive: true,
      unlimitedJobs: true,
    },
    languagesSpoken: ['Tamil', 'English'],
  },
};

export const MOCK_MATCHED_PROVIDERS: MatchedProvider[] = [
  {
    id: 'prov_ravi',
    name: 'Ravi Kumar',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    rating: 4.9,
    reviewCount: 342,
    distanceKm: 2.1,
    etaMinutes: 25,
    verified: true,
    primaryCapability: 'AC Repair & Diagnostics',
    allCapabilities: ['AC Repair', 'AC Service', 'Fan Repair', 'Electrical', 'Bike Repair'],
    diagnosisFee: 149,
    repairPriceNote: 'Decided after diagnosis',
    estimatedPrice: 149,
    experienceYears: 7,
    phone: '+91 98401 22334',
    bio: 'Certified HVAC & multi-skill technician with 7+ years on-field experience in Adyar & South Chennai. Background verified, 30-day warranty.',
    badges: ['Top Rated Pro', 'Multi-Skilled', 'Speedy Arrival'],
  },
  {
    id: 'prov_senthil',
    name: 'Senthil Murugan',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
    rating: 4.8,
    reviewCount: 218,
    distanceKm: 3.4,
    etaMinutes: 35,
    verified: true,
    primaryCapability: 'AC Deep Cleaning & Service',
    allCapabilities: ['AC Service', 'Washing Machine', 'Refrigerator', 'Plumbing'],
    diagnosisFee: 149,
    repairPriceNote: 'Decided after diagnosis',
    estimatedPrice: 149,
    experienceYears: 5,
    phone: '+91 97910 88221',
    bio: 'Specialist in jet-pump AC chemical foam wash and home appliance diagnostics. Genuine spare parts only.',
    badges: ['Appliance Specialist', 'Verified Background'],
  },
  {
    id: 'prov_priya',
    name: 'Priya Anand',
    avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
    rating: 4.9,
    reviewCount: 189,
    distanceKm: 4.2,
    etaMinutes: 40,
    verified: true,
    primaryCapability: 'Electrical & Inverter Setup',
    allCapabilities: ['Electrical', 'AC Service', 'Fan Installation', 'Smart Lighting'],
    diagnosisFee: 149,
    repairPriceNote: 'Decided after diagnosis',
    estimatedPrice: 149,
    experienceYears: 6,
    phone: '+91 94441 55667',
    bio: 'Licensed electrical engineer handling residential load calculation, inverter wiring, and split AC power points.',
    badges: ['Certified Electrician', 'Safety First'],
  },
];

export const MOCK_DEMAND_OPPORTUNITIES: JobOpportunity[] = [
  {
    id: 'job_opp_01',
    serviceName: 'AC Deep Service & Gas Leak Check',
    category: 'HVAC & Cooling',
    customerArea: 'Adyar (near Gandhi Nagar Park)',
    distanceKm: 2.1,
    requestedTime: 'Tomorrow · 6:00 PM',
    diagnosisFee: 149,
    repairPriceDecidedAfterDiagnosis: true,
    serviceMode: 'DIAGNOSIS',
    urgency: 'NORMAL',
    status: 'ELIGIBLE',
    requiredCapability: 'AC_SERVICE',
    customerNameMasked: 'Ramesh K. (Adyar)',
    issueDescription: 'Split AC indoor water dropping and cooling is weak since 2 days.',
    announcementTamil: 'உங்களுக்கு ஒரு புதிய AC service request வந்திருக்கு. கஸ்டமர் நாளைக்கு மாலை 6 மணிக்கு கேட்டிருக்காரு. தூரம் 2.1 கி.மீ. பரிசோதனைக் கட்டணம் ₹149. ரிப்பேர் கட்டணம் பரிசோதனைக்குப் பிறகு. Accept பண்ணலாமா?',
    announcementEnglish: 'New AC service request near Adyar. Tomorrow at 6:00 PM. 2.1 km away. Diagnosis fee ₹149. Repair price decided after diagnosis.',
  },
  {
    id: 'job_opp_02',
    serviceName: 'Ceiling Fan Humming & Speed Regulator',
    category: 'Electrical',
    customerArea: 'Besant Nagar (4th Main Road)',
    distanceKm: 1.8,
    requestedTime: 'Today · 7:30 PM',
    diagnosisFee: 149,
    repairPriceDecidedAfterDiagnosis: true,
    serviceMode: 'DIAGNOSIS',
    urgency: 'URGENT',
    status: 'ELIGIBLE',
    requiredCapability: 'FAN_REPAIR',
    customerNameMasked: 'Priya V. (Besant Nagar)',
    issueDescription: 'Living room fan running very slowly at speed 5 with loud humming noise.',
    announcementTamil: 'அவசர மின்சார உதவி! பேசன்ட் நகரில் ஃபேன் ரிப்பேர் கோரிக்கை. இன்றைக்கு இரவு 7:30 மணி. தூரம் 1.8 கிலோமீட்டர். பரிசோதனைக் கட்டணம் ₹149. ரிப்பேர் கட்டணம் பரிசோதனைக்குப் பிறகு.',
    announcementEnglish: 'Urgent electrical request in Besant Nagar. Fan repair today at 7:30 PM. Approx 1.8 km. Diagnosis fee ₹149. Repair price decided after diagnosis.',
  },
  {
    id: 'job_opp_03',
    serviceName: 'Two-Wheeler Starting Trouble & Spark Plug',
    category: 'Automotive',
    customerArea: 'Thiruvanmiyur (Near RTO)',
    distanceKm: 3.2,
    requestedTime: 'Tomorrow · 9:00 AM',
    diagnosisFee: 0,
    repairPriceDecidedAfterDiagnosis: false,
    serviceMode: 'SERVICE',
    urgency: 'NORMAL',
    status: 'ELIGIBLE',
    requiredCapability: 'BIKE_REPAIR',
    customerNameMasked: 'Vignesh S. (Thiruvanmiyur)',
    issueDescription: 'Honda Activa not kick-starting after rain. Suspected water in carburettor or plug.',
    announcementTamil: 'திருவான்மியூரில் நேரடி டூ-வீலர் சர்வீஸ் ரிக்வெஸ்ட். நாளை காலை 9 மணிக்கு. தூரம் 3.2 கிலோமீட்டர். வாடிக்கையாளர் நேரடியாக சர்வீஸ் அல்லது ரிப்பேர் கேட்டுள்ளார். Accept பண்ணலாமா?',
    announcementEnglish: 'Direct two-wheeler service request in Thiruvanmiyur tomorrow 9:00 AM. Approx 3.2 km. Service / Repair requested.',
  },
];

export const MOCK_INITIAL_BOOKINGS: Booking[] = [
  {
    id: 'bk_active_01',
    referenceCode: 'NXD-89241',
    customerId: 'usr_nexdo_001',
    customerName: 'Hariharasudhan',
    customerPhone: '9876543210',
    provider: MOCK_MATCHED_PROVIDERS[0],
    serviceTitle: 'Split AC Deep Diagnostics & Repair',
    scheduledTime: 'Tomorrow at 6:00 PM',
    address: '42, Sengunthapuram 3rd Cross, Karur, TN 639002',
    status: 'TECHNICIAN_ON_THE_WAY',
    estimatedPrice: 1100,
    otpCode: '4821',
    createdAt: '2026-09-11T14:30:00Z',
    serviceMode: 'DIAGNOSIS',
    notes: 'Indoor unit not cooling, capacitor issue suspected',
    diagnosis: {
      fee: 149,
      findings: 'Capacitor failure detected. Motor coil and compressor pressure verified.',
      isPaid: false,
      otp: '4821',
      isVerified: false,
    },
    estimate: {
      parts: 700,
      labour: 400,
      total: 1100,
      description: 'Dual Run Capacitor 45/5 MFD replacement + electrical safety check',
      isApproved: false,
      isPriceLocked: false,
    },
    payment: {
      status: 'PENDING',
      amount: 1100,
      transactionId: 'TXN_NXD89241',
      qrCodeData: 'NEXDO_TXN_NXD89241_AMT1100',
      isSandbox: true,
    },
    finalOtp: {
      code: '8942',
      isVerified: false,
    },
  },
  {
    id: 'bk_past_01',
    referenceCode: 'NXD-77190',
    customerId: 'usr_nexdo_001',
    customerName: 'Hariharasudhan',
    customerPhone: '9876543210',
    provider: MOCK_MATCHED_PROVIDERS[1],
    serviceTitle: 'Ceiling Fan Capacitor Replacement',
    scheduledTime: 'Sep 8, 2026 at 11:30 AM',
    address: '42, Sengunthapuram 3rd Cross, Karur, TN 639002',
    status: 'COMPLETED',
    estimatedPrice: 350,
    otpCode: '9103',
    createdAt: '2026-09-08T09:15:00Z',
    review: {
      rating: 5,
      comment: 'Very polite technician, fixed the speed problem in 20 minutes.',
      tags: ['Punctual', 'Expert Work', 'Clean Up Done'],
    },
  },
];

export const MOCK_TECHNICIAN_EARNINGS: TechnicianEarnings = {
  todayEarnings: 1100,
  thisWeekEarnings: 6850,
  thisMonthEarnings: 28400,
  totalJobs: 342,
  platformFeeCharged: 0,
  activeSubscriptionTitle: 'Monthly Unlimited Access Pass',
  recentPayouts: [
    { id: 'pay_01', date: 'Today, 2:15 PM', jobTitle: 'AC Jet Cleaning (2 Units)', amount: 1100, customerMasked: 'Anand R. (Besant Nagar)' },
    { id: 'pay_02', date: 'Yesterday, 6:00 PM', jobTitle: 'MCB Tripping Fix', amount: 450, customerMasked: 'Kavitha M. (Adyar)' },
    { id: 'pay_03', date: 'Sep 9, 11:00 AM', jobTitle: 'Fan Motor Bearing Replacement', amount: 600, customerMasked: 'Murugan G. (Kotturpuram)' },
    { id: 'pay_04', date: 'Sep 8, 4:30 PM', jobTitle: 'Split AC Gas Top-up', amount: 1250, customerMasked: 'Deepak S. (Thiruvanmiyur)' },
  ],
};
